apiVersion: v1
kind: Namespace
metadata:
  name: auth-test
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: auth-pod
  namespace: auth-test
spec:
  hard:
    requests.cpu: "500m"  # Very small CPU request budget
    requests.memory: "500Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: stress
        image: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-deployment-hpa
  namespace: auth-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-deployment
  minReplicas: 6
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
